#!/bin/bash
#
# $Header: 
#
# orachk_json_formatter.sh
#
#    NAME
#      orachk_json_formatter.sh - Format JSON file generated by orachk
#
#    DESCRIPTION
#      Format JSON file generated by orachk
#
#    NOTES
#      Usage: orachk_json_formatter.sh <ORACHK_JSON_FILE_NAME>
#
#    AUTHOR
#      Jean Rodrigues
#
#    MODIFIED   (MM/DD/YY)
#    JEANROD    08/03/17 - Creation

# Put commas on JSON objects between curly braces
sed -i 's/\}/&,/' $1

# Remove the last comma
sed -i '$ s/.$//' $1

# Put the brackets in the beginning and end of JSON
sed -i '1s/^/[/' $1
sed -i '$s/$/]/' $1
